application: neon-griffin-788
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: restapi.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest